export const newPalette = {
  primary: {
    light: "#EDFBFF",
    // main: "#47B5FF",
    main: "#2C74D6",
    dark: "#6A95BB",
  },
  secondary: {
    light: "#E6F4F1",
    main: "#9EADBD",
    dark: "#3B4856",
  },
  error: {
    light: "#FEE4E2",
    main: "#D92D20",
    dark: "#B42318",
  },
  warning: {
    light: "#FEEEC5",
    main: "#EEB626",
    dark: "#D1A229",
  },
  success: {
    light: "#D1FADF",
    main: "#12B76A",
    dark: "#039855",
  },
  info: {
    light: "#7EA9E9",
    main: "#1566DE",
    dark: "#1857B6",
  },
  background: {
    default: "#EDEDF7",
    semiPurple: "#EDEDF7",
    grey: "#cfd2cd",
    blue: "#175CD3",
    white: "#ffffff",
    lightgrey: "lightgrey",
    darkgrey: "#6c757d",
    pink: "#ffb3c1",
    darkpink: "#ff4d6d",
    lightblue: "#a2d2ff",
    whitesmoke: "#ffffff",
    offwhite: "#F5F5F5",
  },
  borderFaded: "#f5f5f5",
  borderFaded2: "#eaecf0",
  divider: "#D6D6D6",
  borderColor: "#737373",
  sidebar: {
    background: "#EAECF0",
    popup: "#FCFCFD",
    fadedColor: "#344054",
    color: "#000000",
    heading: "#98A2B3",
    hightlightItem: "#D0D5DD",
    pinkAvatarBack: "#DD2590",
  },
  textColors: {
    grey: "#737373",
    black: "#424242",
    white: "#FFFFFF",
    darkWarning: "#713B12",
    dark: "#1E1E23",
    red: "#912018",
  },
  commonBgColor: {
    lightGrey: "#F9FAFB",
    lightYellow: "#FAC515",
    lightGreen: "#3CB17C",
    lightBlue: "#3788EA",
    paleGrey: "#F0F2F4",
    white: "#FFFFFF",
    solidWhite: "#F2F4F7",
    lightBlueMagenta: "#AEAEBB",
    lightGrayishBlue: "#E9E7FB",
    lightWhiteBlue: "#F8F7FF",
    lightPrimaryBlue: "#478BF1",
    lightCyanBlue: "#E3EDF9",
    lightCyanGreen: "#E6F4F2",
    lightRed: "#FFF4F3",
    darkgrey: "#6c757d",
  },
  shape: {
    borderRadius: {
      small: 8,
      medium: 16,
      large: 20,
    },
  },
  gap: {
    primary: 8,
    main: 16,
    secondary: 20,
    tworem: 32,
    small: 4,
  },
};
